### ISSUE TITLE
設定整合的時候出現錯誤 

### ISSUE THREAD

**Issue by bensoncho** [qqaatw/JciHitachiHA#16]
我的環境是使用樹莓派4安裝 Hassio, 
安裝好整合，在登入的過程中，出現了以下的錯誤
請問能夠怎麼解決呢? 謝謝

環境:
版本 | core-2022.3.1
安裝類型 | Home Assistant OS
開發版 | false
Supervisor | true
Docker | true
使用者 | root
虛擬環境 | false
Python 版本 | 3.9.9
作業系統家族 | Linux
作業系統版本 | 5.10.103-v7l
CPU 架構 | armv7l
時區 | Asia/Taipei

錯誤訊息:
2022-04-09 21:47:26 ERROR (MainThread) [homeassistant.util.package] Unable to install package LibJciHitachi==0.5.0: error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [38 lines of output]
      running bdist_wheel
      running build
      running build_py
      running build_ext
      Traceback (most recent call last):
        File "", line 2, in 
        File "", line 34, in 
        File "/tmp/pip-install-fjn52pbs/awscrt_b83358bc98424627ba69b6e1c4b71c38/setup.py", line 294, in 
          setuptools.setup(
        File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 155, in setup
          return distutils.core.setup(**attrs)
        File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 148, in setup
          return run_commands(dist)
        File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
          dist.run_commands()
        File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/usr/local/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-fjn52pbs/awscrt_b83358bc98424627ba69b6e1c4b71c38/setup.py", line 212, in run
          self._build_dependency(lib)
        File "/tmp/pip-install-fjn52pbs/awscrt_b83358bc98424627ba69b6e1c4b71c38/setup.py", line 154, in _build_dependency
          cmake = get_cmake_path()
        File "/tmp/pip-install-fjn52pbs/awscrt_b83358bc98424627ba69b6e1c4b71c38/setup.py", line 94, in get_cmake_path
          raise Exception("CMake must be installed to build from source.")
      Exception: CMake must be installed to build from source.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for awscrt
  error: subprocess-exited-with-error
  
  × Running setup.py install for awscrt did not run successfully.
  │ exit code: 1
  ╰─> [42 lines of output]
      running install
      /usr/local/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      running build_ext
      Traceback (most recent call last):
        File "", line 2, in 
        File "", line 34, in 
        File "/tmp/pip-install-fjn52pbs/awscrt_b83358bc98424627ba69b6e1c4b71c38/setup.py", line 294, in 
          setuptools.setup(
        File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 155, in setup
          return distutils.core.setup(**attrs)
        File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 148, in setup
          return run_commands(dist)
        File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
          dist.run_commands()
        File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/usr/local/lib/python3.9/site-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
        File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/command/install.py", line 670, in run
          self.run_command('build')
        File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-fjn52pbs/awscrt_b83358bc98424627ba69b6e1c4b71c38/setup.py", line 212, in run
          self._build_dependency(lib)
        File "/tmp/pip-install-fjn52pbs/awscrt_b83358bc98424627ba69b6e1c4b71c38/setup.py", line 154, in _build_dependency
          cmake = get_cmake_path()
        File "/tmp/pip-install-fjn52pbs/awscrt_b83358bc98424627ba69b6e1c4b71c38/setup.py", line 94, in get_cmake_path
          raise Exception("CMake must be installed to build from source.")
      Exception: CMake must be installed to build from source.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure
× Encountered error while trying to install package.
╰─> awscrt
note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
WARNING: You are using pip version 22.0.3; however, version 22.0.4 is available.
You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.
2022-04-09 21:47:26 ERROR (MainThread) [custom_components.jcihitachi_tw.config_flow] Failed to login API: Requirements for jcihitachi_tw not found: ['LibJciHitachi==0.5.0'].
ConnectedD

**Comment by qqaatw** [comment]
您的HAOS應該是裝到32位元版本了。

**Comment by qqaatw** [comment]
您的HAOS應該是裝到32位元版本了。Integration 在 arm arch 只支援64位元，cpu架構應顯示`armv8`。

**Comment by bensoncho** [comment]
非常感謝說明， 我這邊再重新安裝 64 位元版本的作業系統試試 ^^

**Comment by bensoncho** [comment]
安裝 64 位元版本後，已可正常使用 謝謝

**Comment by tomky** [comment]
我試著安裝到container版本的HomeAssistant(跑在pi4的docker上)，也是遇到類似問題。但我的環境已經是aarch64 Linux了，請問有解決方案嗎？

**Comment by qqaatw** [comment]
> 我試著安裝到container版本的HomeAssistant(跑在pi4的docker上)，也是遇到類似問題。但我的環境已經是aarch64 Linux了，請問有解決方案嗎？
> 
> 

Please paste your HA environment information here like what the issue author does.

**Comment by tomky** [comment]
環境:  
版本 | 2023.6.3
安裝類型 | Home Assistant Container
開發版 | false  
Supervisor | true  
Docker | true  
使用者 | root  
虛擬環境 | docker
Python 版本 | 3.11.4
作業系統家族 | Linux  
作業系統版本 | 6.1.21-v8+  
CPU 架構 | aarch64 
時區 | Asia/Taipei

錯誤訊息:  
Logger: homeassistant.setup
Source: setup.py:207 
First occurred: 13:29:37 (1 occurrences) 
Last logged: 13:29:37

Setup failed for custom integration jcihitachi_tw: Requirements for jcihitachi_tw not found: ['LibJciHitachi==1.3.0'].

**Comment by qqaatw** [comment]
Are there more error messages related to this? If so, please paste them as
complete as possible so we can identify which dependent package is not
found exactly.

**Comment by tomky** [comment]
2023-09-05 15:11:26.638 ERROR (SyncWorker_3) [homeassistant.util.package] Unable to install package LibJciHitachi==1.3.0: error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-aarch64-cpython-311
      creating build/lib.linux-aarch64-cpython-311/awscrt
      copying awscrt/websocket.py -> build/lib.linux-aarch64-cpython-311/awscrt
      copying awscrt/mqtt5.py -> build/lib.linux-aarch64-cpython-311/awscrt
      copying awscrt/io.py -> build/lib.linux-aarch64-cpython-311/awscrt
      copying awscrt/exceptions.py -> build/lib.linux-aarch64-cpython-311/awscrt
      copying awscrt/common.py -> build/lib.linux-aarch64-cpython-311/awscrt
      copying awscrt/s3.py -> build/lib.linux-aarch64-cpython-311/awscrt
      copying awscrt/mqtt.py -> build/lib.linux-aarch64-cpython-311/awscrt
      copying awscrt/crypto.py -> build/lib.linux-aarch64-cpython-311/awscrt
      copying awscrt/checksums.py -> build/lib.linux-aarch64-cpython-311/awscrt
      copying awscrt/_test.py -> build/lib.linux-aarch64-cpython-311/awscrt
      copying awscrt/http.py -> build/lib.linux-aarch64-cpython-311/awscrt
      copying awscrt/__init__.py -> build/lib.linux-aarch64-cpython-311/awscrt
      copying awscrt/auth.py -> build/lib.linux-aarch64-cpython-311/awscrt
      creating build/lib.linux-aarch64-cpython-311/awscrt/eventstream
      copying awscrt/eventstream/rpc.py -> build/lib.linux-aarch64-cpython-311/awscrt/eventstream
      copying awscrt/eventstream/__init__.py -> build/lib.linux-aarch64-cpython-311/awscrt/eventstream
      running build_ext
      > /usr/bin/cmake -H/tmp/pip-install-xm3_llgr/awscrt_381a79b1840243b7a05e25eee286a002/crt -Bbuild/temp.linux-aarch64-cpython-311/deps -DCMAKE_INSTALL_PREFIX=build/temp.linux-aarch64-cpython-311/deps/install -DCMAKE_BUILD_TYPE=RelWithDebInfo
      error: [Errno 2] No such file or directory: '/usr/bin/cmake'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for awscrt
ERROR: Could not build wheels for awscrt, which is required to install pyproject.toml-based projects

**Comment by qqaatw** [comment]
What's the output of this commend `getconf LONG_BIT` typed in your host OS?

If not 64, then your Host OS is of 32 bit.

**Comment by tomky** [comment]
Thanks for the info. It does output 32. So it is likely the problem of my host OS... I will reinstall and give it another try.
