### ISSUE TITLE
安裝整合產生錯誤

### ISSUE THREAD

**Issue by TEKTEKC** [qqaatw/JciHitachiHA#27]
安裝平台：Pi4
Home Assistant Core 2022.6.6

您好：
今天看日誌發現出現以下錯誤，有時重新開機，整合會啟動失敗，需關閉重啟，特此回報。

感謝！

自行安裝整合產生錯誤。

Logger: homeassistant.config_entries
Source: custom_components/jcihitachi_tw/__init__.py:168
Integration: JciHitachi TW (documentation, issues)
First occurred: 07:28:51 (1 occurrences)
Last logged: 07:28:51

Error setting up entry JciHitachi TW for jcihitachi_tw
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 339, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/jcihitachi_tw/__init__.py", line 168, in async_setup_entry
    f"Thing info: {[thing for thing in api.things.values()]}")
  File "/usr/local/lib/python3.9/site-packages/JciHitachi/api.py", line 629, in __repr__
    f"brand: {self.brand}\n"
  File "/usr/local/lib/python3.9/site-packages/JciHitachi/api.py", line 705, in brand
    return getattr(self._support_code, "Brand")
AttributeError: 'NoneType' object has no attribute 'Brand'

**Comment by qqaatw** [comment]
跟你確認一下帳號內有幾台裝置加入HA。
