### ISSUE TITLE
Can't put into integration

### ISSUE THREAD

**Issue by TwKenYang** [qqaatw/JciHitachiHA#49]
### 🐛 Describe the bug

Cannot quick reload all YAML configurations because the configuration is not valid: Integration error: jcihitachi_tw - Integration 'jcihitachi_tw' not found.

Logger: homeassistant.components.websocket_api.http.connection
Source: components/homeassistant/__init__.py:316
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 01:01:38 (1 occurrences)
Last logged: 01:01:38

[547489919808] Cannot quick reload all YAML configurations because the configuration is not valid: Integration error: jcihitachi_tw - Integration 'jcihitachi_tw' not found.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1849, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1889, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 874, in admin_handler
    await result
  File "/usr/src/homeassistant/homeassistant/components/homeassistant/__init__.py", line 316, in async_handle_reload_all
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Cannot quick reload all YAML configurations because the configuration is not valid: Integration error: jcihitachi_tw - Integration 'jcihitachi_tw' not found.

Logger: homeassistant.components.homeassistant
Source: components/homeassistant/__init__.py:312
Integration: Home Assistant Core Integration (documentation, issues)
First occurred: 01:01:38 (1 occurrences)
Last logged: 01:01:38

The system cannot reload because the configuration is not valid: Integration error: jcihitachi_tw - Integration 'jcihitachi_tw' not found.

### Environment Information

RAC-50YK2/RAS-50YSK
Home Assistant 2023.5.3
Pi 4

**Comment by qqaatw** [comment]
This is expected, please reboot your home assistant when the integration is installed and configured via yaml first time.
