### ISSUE TITLE
Error during setup of component jcihitachi_tw

### ISSUE THREAD

**Issue by harry2690** [qqaatw/JciHitachiHA#65]
### 🐛 Describe the bug

I updated to version 1.6.0, and then I received this error message:

```
Logger: homeassistant.setup
Source: setup.py:332
First occurred: 下午1:38:45 (1 occurrences)
Last logged: 下午1:38:45

Error during setup of component jcihitachi_tw
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 332, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/jcihitachi_tw/__init__.py", line 94, in async_setup
    await hass.async_add_executor_job(api.login)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/JciHitachi/api.py", line 1015, in login
    self._mqtt.configure(self._aws_identity.identity_id)
  File "/usr/local/lib/python3.11/site-packages/JciHitachi/aws_connection.py", line 706, in configure
    self._mqttc = mqtt_connection_builder.websockets_with_default_aws_signing(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/awsiot/mqtt_connection_builder.py", line 444, in websockets_with_default_aws_signing
    return websockets_with_custom_handshake(_sign_websocket_handshake_request, websocket_proxy_options, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/awsiot/mqtt_connection_builder.py", line 477, in websockets_with_custom_handshake
    return _builder(tls_ctx_options=tls_ctx_options,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/awsiot/mqtt_connection_builder.py", line 235, in _builder
    return awscrt.mqtt.Connection(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/awscrt/mqtt.py", line 412, in __init__
    self._binding = _awscrt.mqtt_client_connection_new(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: function takes exactly 3 arguments (4 given)

```

### Environment Information

Core 2023.12.4
Supervisor 2023.12.0

**Comment by harry2690** [comment]
Later, I removed the settings inside `configuration.yaml`, reconfigured using the add integration, and it worked fine.

**Comment by harry2690** [comment]
Later, I removed the settings inside `configuration.yaml`, reconfigured using the add integration, and it worked fine.
