### ISSUE TITLE
Error while setting up jcihitachi_tw platform for climate

### ISSUE THREAD

**Issue by jj-tw** [qqaatw/JciHitachiHA#93]
### 🐛 Describe the bug

以前ha多重開機幾次，就能用，這次無論怎麼重開都沒有用
JciHitachiHA 版本也試過好幾個，但依舊顯示如下的錯誤
在ha裡顯示 由 jcihitachi_tw 整合所提供的實體無法使用，假如該實體已不再使用，請於設定中進行移除。

Logger: homeassistant.components.climate
Source: custom_components/jcihitachi_tw/climate.py:259
Integration: 溫控 ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 03:39:46 (1 occurrences)
Last logged: 03:39:46

Error while setting up jcihitachi_tw platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/jcihitachi_tw/climate.py", line 87, in async_setup_entry
    await _async_setup(hass, async_add_devices)
  File "/config/custom_components/jcihitachi_tw/climate.py", line 77, in _async_setup
    [JciHitachiClimateEntity(thing, coordinator)],
  File "/config/custom_components/jcihitachi_tw/climate.py", line 93, in __init__
    self._supported_features = self.calculate_supported_features()
  File "/config/custom_components/jcihitachi_tw/climate.py", line 259, in calculate_supported_features
    support_flags = ClimateEntityFeature.TURN_ON | ClimateEntityFeature.TURN_OFF | ClimateEntityFeature.TARGET_TEMPERATURE | ClimateEntityFeature.FAN_MODE | ClimateEntityFeature.PRESET_MODE
  File "/usr/local/lib/python3.10/enum.py", line 437, in __getattr__
    raise AttributeError(name) from None
AttributeError: TURN_ON

### Environment Information

ha core 2023.3.4
JciHitachiHA 1.9.0

**Comment by qqaatw** [comment]
HA core is out-dated.

**Comment by jj-tw** [comment]
請問有辦法可以更新core到指定升級的版本嗎？
因為有些東西更新到太新的core無法使用

**Comment by qqaatw** [comment]
```
2024.2.0
git tag --contain bc720b48b476d2fa1ad754166d6aca72e0d180cf | sort -n -r -t '.' -k2,3
```

At least `2024.2.0` onwards.
